# Generated by Django 5.0.2 on 2024-03-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
